apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
    spec:
      containers:
      - image: mohdhakimimohdnor/house-price-model:latest
        name: house-price-model
        ports:
        - containerPort: 8000
        - containerPort: 9100        
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
              cpu: "100m"
              memory: "128Mi"
status: {}
